apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: eventscheduler
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value:            "ghcr.io/rprakashg-redhat/rhacs-policy-management/backend@sha256:c1d326a22c5819bbe4ffc530f7a5dd73f1d1a93660a5d8429c9300441836ad1e"
