apiVersion: apps/v1
kind: Deployment
metadata:
  name: ormdemo
  labels:
    app: ormdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ormdemo
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ormdemo
    spec:
      containers:
      - name: ormdemo
        image: "{applied through kustomize}"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: POSTGRESCLUSTER_USER
          valueFrom:
            secretKeyRef:
              name: db-connection-properties
              key: DBUSER
              optional: false
        - name: POSTGRESCLUSTER_USER_PWD
          valueFrom:
            secretKeyRef:
              name: db-connection-properties
              key: DBPASSWORD
              optional: false
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: db-connection-properties
              key: DBHOST
              optional: false
        - name: DBNAME
          valueFrom:
            secretKeyRef:
              name: db-connection-properties
              key: DBNAME
              optional: false
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 64Mi
      imagePullSecrets:
      - name: ghcr-creds