apiVersion: v1
kind: Service
metadata:
  name: eventscheduler
  labels:
    app: eventscheduler
    service: eventscheduler
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: eventscheduler
    role: backend