name: cd
on:
  push:
    branches:
      - main
    paths:
      - "deploy/apps/**"
  workflow_dispatch:
jobs:
  deploy:
    name: deploy apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: verify tools installed
      run: |
        kubectl version --client=true
        aws --version


  