name: cd
on:
  push:
    branches:
      - main
    paths:
    - deploy/apps/backend
    - deploy/apps/frontend
jobs:
  deploy:
    name: deploy apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
