name: cd
on:
  push:
    branches:
      - main
    paths:
      - "deploy/apps/**"
  workflow_dispatch:
jobs:
  deploy:
    name: deploy apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: download tools
      run: |
        # download required tools
        mkdir $HOME/bin
    - name: verify tools installed
      run: |
        kubectl version
        aws --version
        

  