name: cd
on:
  push:
    branches:
      - main
    paths:
      - "deploy/apps/**"
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  deploy:
    name: deploy apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: verify tools installed
      run: |
        kubectl version --client=true
        aws --version
    - name: get cluster credentials
      run: |
        aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.CLUSTER_NAME }}
        kubectl get nodes
    - name: create namespace
      run: |
        kubectl create namespace "quarkus-quickstarts" --dry-run=client -o yaml | kubectl apply -f -
    - name: create image pull secret
      run: |
        kubectl create secret docker-registry ghcr-creds --docker-server=https://ghcr.io --docker-username=rprakashg-redhat --docker-password=${{ secrets.IMAGE_PULL_TOKEN }} --docker-email=rgopinat@redhat.com




  