name: ci
on:
  push:
    branches:
      - main
    paths:
    - "apps/**"
  workflow_dispatch:
env:
  IMAGE_TAGS: ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:

  build-graph:
    name: build graphql server microservice
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push-to-registry.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: apps/graph/yarn.lock
      - name: build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: rhacs-policy-management/graph
          tags: ${{ env.IMAGE_TAGS }}
          context: apps/graph
          containerfiles: |
            apps/graph/Dockerfile
      - name: push container image to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: rhacs-policy-management/graph
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

  update-graph-manifests:
    name: update graph manifests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup git
      run: |
        # Setting up the git config.
        git config --global user.email "rgopinat@redhat.com" # HARD CODING FOR NOW, NEED TO DETERMINE HOW TO RETRIEVE THIS FROM CURRENT USER CONTEXT
        git config --global user.name ${{ github.actor }}
    - name: update deployment manifest for backend microservice
      working-directory: deploy/apps/graph
      run: |
        IMAGE=\"${{ env.IMAGE_REGISTRY }}/rhacs-policy-management/graph@${{ needs.build-graph.outputs.digest }}\"
        git checkout -b "${{ github.actor }}-${{ github.sha }}"
        sed -i "s#\(.*value:\s*\).*#\1 ${IMAGE}#" overlays/dev/kustomization.yaml

        git add .
        git commit -m "updated manifest to point to image tag $IMAGE"
        git push origin "${{ github.actor }}-${{ github.sha }}"
    needs: build-graph

  #open pull request on merge will trigger deployment workflow
  open-pr:
    name: open pull request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup git
      run: |
        # Setting up the git config.
        git config --global user.email "rgopinat@redhat.com" # HARD CODING FOR NOW, NEED TO DETERMINE HOW TO RETRIEVE THIS FROM CURRENT USER CONTEXT
        git config --global user.name ${{ github.actor }}
    - name: create pr
      run: |
        gh pr create --body "PR for commit - ${{ github.sha }} by {{ github.actor }}" --title "PR for commit - ${{ github.sha }}" --base main --head "{{ github.actor }}-${{ github.sha }}" 
      env:
        GH_TOKEN: ${{ github.token }}
    needs: [update-graph-manifests]