name: ci
on:
  push:
    branches:
      - main
    paths:
    - "apps/**"
  workflow_dispatch:
env:
  IMAGE_TAGS: ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-backend:
    name: build java/quarkus based backend microservice 
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push-to-registry.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      - name: setup git
        run: |
          # Setting up the git config.
          git config --global user.email "rgopinat@redhat.com" # HARD CODING FOR NOW, NEED TO DETERMINE HOW TO RETRIEVE THIS FROM CURRENT USER CONTEXT
          git config --global user.name ${{ github.actor }}
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: maven build
        working-directory: ./apps/backend
        run: ./mvnw clean install
      - name: container build
        uses: redhat-actions/buildah-build@v2
        with:
          image: rhacs-policy-management/backend
          tags: ${{ env.IMAGE_TAGS }}
          context: apps/backend
          containerfiles: |
            apps/backend/src/main/docker/Dockerfile.jvm
      - name: push to github registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: rhacs-policy-management/backend
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
        
  build-graph:
    name: build graphql server microservice
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push-to-registry.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: apps/graph/yarn.lock
      - name: install dependencies
        working-directory: apps/graph
        run: |
          yarn install --frozen-lockfile
      - name: build
        working-directory: apps/graph
        run: |
          yarn run build
        #env:
        #  DATABASE_URL: "mongodb://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_USER_PASSWORD }}@${{ secrets.MONGODB_HOST }}/${{ secrets.MONGODB_DB_NAME }}"
      - name: build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: rhacs-policy-management/graph
          tags: ${{ env.IMAGE_TAGS }}
          context: apps/graph
          containerfiles: |
            apps/graph/Dockerfile
      - name: push container image to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: rhacs-policy-management/graph
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

  update-deployment-manifests:
    name: update deployment manifests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup git
      run: |
        # Setting up the git config.
        git config --global user.email "rgopinat@redhat.com" # HARD CODING FOR NOW, NEED TO DETERMINE HOW TO RETRIEVE THIS FROM CURRENT USER CONTEXT
        git config --global user.name ${{ github.actor }}
    - name: create branch
      run: |
        git checkout -b "${{ github.job }}-${{ github.sha }}"
    - name: update deployment manifest for backend microservice
      working-directory: deploy/apps/backend
      run: |
        IMAGE=\"${{ env.IMAGE_REGISTRY }}/rhacs-policy-management/backend@${{ needs.build-backend.outputs.digest }}\"
        sed -i "s#\(.*value:\s*\).*#\1 ${IMAGE}#" overlays/dev/kustomization.yaml
    - name: update deployment manifest for graphql server
      working-directory: deploy/apps/graph
      run: |
        IMAGE=\"${{ env.IMAGE_REGISTRY }}/rhacs-policy-management/graph@${{ needs.build-graph.outputs.digest }}\"
        sed -i "s#\(.*value:\s*\).*#\1 ${IMAGE}#" overlays/dev/kustomization.yaml
    - name: commit changes to upstream
      run: |
        git add .
        git commit -m "updated deployment manifests to deploy new versions of apps"
        git push origin "${{ github.job }}-${{ github.sha }}"
    needs: [build-backend, build-graph]

  #open pull request on merge will trigger deployment workflow
  open-pr:
    name: open pull request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup git
      run: |
        # Setting up the git config.
        git config --global user.email "rgopinat@redhat.com" # HARD CODING FOR NOW, NEED TO DETERMINE HOW TO RETRIEVE THIS FROM CURRENT USER CONTEXT
        git config --global user.name ${{ github.actor }}
    - name: create pr
      run: |
        gh pr create --body "PR for commit - ${{ github.sha }} by {{ github.actor }}" --title "PR for commit - ${{ github.sha }}" --base main --head "update-deployment-manifests-${{ github.sha }}" 
      env:
        GH_TOKEN: ${{ github.token }}
    needs: [update-deployment-manifests]